### ISSUE TITLE
Refreshing channels fails

### ISSUE THREAD

**Issue by enron-hubbard** [sarowish/ytsub#2]
Environment: manjaro-sway
Version: 0.3.1-1
Expected Behavior: All Channels refresh

Behavior:

When attempting to refresh all channels with Shift-R> ytsub panicks and crashes with the following message:
```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/channel.rs:100:9
```
This behavior recurs using AUR installs for ytsub, ytsub-git, and ytsub-bin. It also recurs in the cargo install.

**Comment by sarowish** [comment]
There have been changes in the Invidious API so refreshing failed when using up-to-date instances. Refreshing should work now with the commit https://github.com/sarowish/ytsub/commit/d9ef233cd5cdbb7b19b038d26ddfba2a5633270c.

**Comment by enron-hubbard** [comment]
Looks like changing to a different Invidious instance prevents this from recurring. Thanks!
