### ISSUE TITLE
"ytsub -g" generates a 0 byte instances file

### ISSUE THREAD

**Issue by S22F5** [sarowish/ytsub#4]
## Description
when ytsub -g doesnt find any instances it will generate a 0 byte instances file.
ytsub will try to generate a random number from 0 to 0 causing a program crash
https://github.com/sarowish/ytsub/blob/d28a4cff01e2b8cbe66ddb07f6717c410a3a7083/src/api/invidious.rs#L50

## Possible Solution:
add a simple newline into the instances file after generation
add a range check before the offending code
if needed add a warning that no instances could be found

## Steps to Reproduce: 
1. run `touch ~/.config/ytsub/instances` OR disable networking and run `ytsub -g`
2. run `ytsub`

## Backtrace:
stack backtrace:
   0:      0xda34ab955c2 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hfa18e0fb89b78135
   1:      0xda34abbfe53 - core::fmt::write::h720837234efe462a
   2:      0xda34ab90abf - std::io::Write::write_fmt::hd216aacc6845c401
   3:      0xda34ab95472 - std::sys::backtrace::BacktraceLock::print::h31c66b38f3579e90
   4:      0xda34ab967ce - std::panicking::default_hook::{{closure}}::hadacae615ce1ff60
   5:      0xda34ab96610 - std::panicking::default_hook::hde7ba89eba787ec1
   6:      0xda34ab96de2 - std::panicking::rust_panic_with_hook::h3ca700fbfdc8bc09
   7:      0xda34ab96c36 - std::panicking::begin_panic_handler::{{closure}}::hc4913e34838e09da
   8:      0xda34ab95a89 - std::sys::backtrace::__rust_end_short_backtrace::hcf902e9d29d24ab0
   9:      0xda34ab968cc - rust_begin_unwind
  10:      0xda34a8f9d70 - core::panicking::panic_fmt::h68842d4a61e10377
  11:      0xda34a8f9dfc - core::panicking::panic::hee38f5bf95801f81
  12:      0xda34a974372 - rand::rng::Rng::gen_range::h8e4914c4ecfd4caf
  13:      0xda34a912665 - ytsub::api::invidious::Instance::new::h8a26b6db9dd5805a
  14:      0xda34a8ffaa8 - ytsub::app::App::new::hee64e4374616c963
  15:      0xda34a9386b3 - ytsub::main::h5504c99096150111
  16:      0xda34a9a9c46 - std::sys::backtrace::__rust_begin_short_backtrace::h00085945fe0d8140
  17:      0xda34a988841 - std::rt::lang_start::{{closure}}::hc9b5dfcbdfd685d5
  18:      0xda34ab8b25e - std::rt::lang_start_internal::hae4dfaa265720ccd
  19:      0xda34a93a1f4 - main
  20:     0x6bd2c0851e08 - <unknown>
  21:     0x6bd2c0851ecc - __libc_start_main
  22:      0xda34a8fa575 - _start
  23:                0x0 - <unknown>

**Comment by sarowish** [comment]
I already tried to address this issue with https://github.com/sarowish/ytsub/commit/3c30588 and I am not getting any crashes with an empty instances file when i try it on the latest `master`. Were you using an older version? If so, also beware that the app no longer uses the Invidious API by default.

**Comment by S22F5** [comment]
already fixed. was on v4.0 updated to latest git. issue resolved
feel free to delete
